services:
    web_interface:
        image: node:hydrogen-slim
        container_name: WEB-Interface
        command: /bin/sh -c "cd /srv/app && npm install && npm run dev"
        ports:
            - '3000:3000'
        working_dir: /srv/app
        volumes:
            - type: bind
              source: ./
              target: /srv/app
            - type: bind
              source: ../audio
              target: /srv/app/audio
        tty: true
